

[package]

name = "z-tokens-exchange-tool"

workspace = "../workspace"

autobins = false
autoexamples = false
autotests = false
autobenches = false

version.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true




[lib]

name = "z_tokens_exchange_tool"
path = "./lib.rs"




[features]

default = [
	"z-tokens-runtime/default",
]

development = [
	"z-tokens-runtime/development",
]

release = [
	"z-tokens-runtime/release",
]




[dependencies]

z-tokens-runtime = { path = "../runtime", default-features = false, features = [] }

vrl-errors = { version = "*", default-features = false, features = [] }
vrl-preludes = { version = "*", default-features = false, features = [] }

x25519-dalek = { version = "*", default-features = false, features = ["std", "u64_backend"] }
salsa20 = { version = "*", default-features = false, features = ["std"] }
blake3 = { version = "*", default-features = false, features = ["std"] }
constant_time_eq = { version = "*", default-features = false, features = [] }
block-padding = { version = "*", default-features = false, features = ["std"] }
bech32 = { version = "*", default-features = false, features = ["std"] }
rand = { version = "*", default-features = false, features = ["std", "getrandom"] }
brotli = { version = "*", default-features = false, features = ["std"] }
byteorder = { version = "*", default-features = false, features = [] }
bs58 = { version = "*", default-features = false, features = ["std"] }
crc-any = { version = "*", default-features = false, features = [] }


