

[package]

name = "z-tokens-patterns-tool"
version = "0.1.0"
publish = false

edition = "2021"
rust-version = "1.63"

autobins = false
autoexamples = false
autotests = false
autobenches = false

workspace = "../workspace"




[lib]

name = "z_tokens_patterns_tool"
path = "./lib.rs"




[features]

default = [
	"z-tokens-patterns/default",
	"z-tokens-runtime/default",
]

development = [
	"z-tokens-patterns/development",
	"z-tokens-runtime/development",
]

release = [
	"z-tokens-patterns/release",
	"z-tokens-runtime/release",
]




[dependencies]

z-tokens-runtime = { path = "../runtime" }
z-tokens-patterns = { path = "../patterns" }

vrl-errors = { version = "*", default-features = false, features = [] }
vrl-preludes = { version = "*", default-features = false, features = [] }

argparse = { version = "*", default-features = false, features = [] }


